### ISSUE TITLE
How do I provide CODE / CONTENT grammars?

### ISSUE THREAD

**Issue by colelawrence** [tree-sitter/tree-sitter-embedded-template#1]
I've read through http://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners
And read through the source code of this repo, and then I started looking at http://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents

But, I'm not entirely sure where the boundaries are between the parser (produced by `tree-sitter generate`) and the rust bindings I'm attempting to make.

Is there another resource that I might be missing?

Cheers!

**Comment by maxbrunsfeld** [comment]
The documentation section that you linked provides a full example of parsing an ERB file with this repo, [tree-sitter-html](https://github.com/tree-sitter/tree-sitter-html) and [tree-sitter-ruby](https://github.com/tree-sitter/tree-sitter-ruby), in terms of the raw C API.

The Rust API has all of the same concepts as the C API, so you could try following along with that example, but using the corresponding Rust [Parser APIs](https://docs.rs/tree-sitter/0.3.10/tree_sitter/struct.Parser.html). Apologies that these methods don't have docs yet. I will write that up soon. But they mostly correspond 1:1 with the documented C APIs.

**Comment by colelawrence** [comment]
Thank you for the additional information.
