### ISSUE TITLE
Cannot get syntax highlighting

### ISSUE THREAD

**Issue by hamidreza4dev** [tree-sitter/tree-sitter-embedded-template#17]
Hi, I installed the plugin but I can't have syntax highlighting.
I also typed these commands:
:TSInstall ejs
:TSBufEnable hightlight

My config repo : https://github.com/hamidreza4dev/dotfiles

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/69403093/202859480-61026ec1-5a81-4ec9-915e-51a40b88db66.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/69403093/202859424-30305623-d880-405b-83bf-97b256d25acd.png">

**Comment by hamidreza4dev** [comment]
Changing the file extension to html and changing it again to ejs solves the problem. Do you have any opinion at all?

**Comment by hamidreza4dev** [comment]
> ```lua
> local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
> parser_config.embedded_template = {
>   install_info = {
>     url = "https://github.com/tree-sitter/tree-sitter-embedded-template",
>     files = {"src/parser.c"},
>     requires_generate_from_grammar = false,
>   },
> }
> 
> local ft_to_parser = require"nvim-treesitter.parsers".filetype_to_parsername
> ft_to_parser.ejs = "embedded_template"
> 
> vim.api.nvim_create_autocmd({"BufRead", "BufNewFile"}, {
>   pattern = "*.ejs",
>   command = "set filetype=ejs"
> })
> ```
> 
> This works for me without having to install any other plugins. I think issue is that ejs is not a recognized file type so needs to be mapped to the embedded_template file type.

This code worked and syntax highlighting was fixed. Do you have an idea to get auto-completion?

**Comment by p-m-p** [comment]
I'm no expert but you can see my personal configs here https://github.com/p-m-p/nvim-config/blob/main/plugin/cmp.lua
