### ISSUE TITLE
Highlighting Not Working on GitHub.com

### ISSUE THREAD

**Issue by davidmurdoch** [tree-sitter/tree-sitter-embedded-template#27]
I was told this package was used for GitHub.com's syntax highlighting. Please close this if this isn't true.

I've added a `.gitattributes` linguist-language mapping for app's HTML files to EJS:
https://github.com/MetaMask/metamask-extension/blob/0495d5b395bab9f3ec954cdcac84aaf085fc7f98/.gitattributes#L24

But the HTML files aren't syntax highlighted as I'd expect. Example file that lacks EJS syntax highlighting:
https://github.com/MetaMask/metamask-extension/blob/0cd76e5b6a3fe4b491348ac0c348a27a82368a32/app/home.html#L6-L10

**Comment by amaanq** [comment]
Issues shouldn't be opened here for GH's usage of tree-sitter, it's probably better to do that at linguist.
