### ISSUE TITLE
HTML nodes contain ERB code in text node.

### ISSUE THREAD

**Issue by thibaultdalban** [tree-sitter/tree-sitter-embedded-template#5]
Hello,

I'm not sure if it's a bug or if it's me not understanding the parser logic.
I try to parse an ERB file. I followed the provided example using C API, and converted it to use the Node equivalent.
```js
const Parser = require("tree-sitter")
const ERB = require("tree-sitter-embedded-template")
const Ruby = require("tree-sitter-ruby")
const HTML = require("tree-sitter-html")

const parse = function parse(sourceCode) {
  const parser = new Parser()
  parser.setLanguage(ERB)
  const erbTree = parser.parse(sourceCode)
  const erbRootNode = erbTree.rootNode

  const rubyRanges = []
  const htmlRanges = []

  erbRootNode.children.forEach(node => {
    if (node.type === "content") {
      htmlRanges.push({
        startIndex: node.startIndex,
        endPosition: node.endPosition,
        startPosition: node.startPosition,
        endIndex: node.endIndex,
    })
    } else {
      const codeNode = node.namedChild(0)
      if(!codeNode) return
      rubyRanges.push({
        startIndex: codeNode.startIndex,
        endPosition: codeNode.endPosition,
        startPosition: codeNode.startPosition,
        endIndex: codeNode.endIndex,
      })
    }
  })

  parser.setLanguage(Ruby)
  const rubyTree = parser.parse(
    sourceCode,
    undefined,
    { includedRanges: rubyRanges }
  )
  const rubyRootNode = rubyTree.rootNode

  parser.setLanguage(HTML)
  const htmlTree = parser.parse(
    sourceCode,
    undefined,
    { includedRanges: htmlRanges }
  )
  const htmlRootNode = htmlTree.rootNode

  const erb_sexp = erbRootNode.toString()
  const html_sexp = htmlRootNode.toString()
  const ruby_sexp = rubyRootNode.toString()

  console.log(`ERB: ${erb_sexp}`)
  console.log(`HTML: ${html_sexp}`)
  console.log(`RUBY: ${ruby_sexp}`)
}
```
When I run the following code:
```js
parse("<ul><%= person.name %></ul>")
```
It outputs:
- ERB: (template (content) (output_directive (code)) (content))
- HTML: (fragment (element (start_tag (tag_name)) (end_tag (tag_name))))
- RUBY: (program (call receiver: (identifier) method: (identifier)))

Ruby part is correctly excluded from the HTML.

When I run the following code (note the space before the </ul> ending tag):
```js
parse("<ul><%= person.name %> </ul>")
```
It outputs:
- ERB: (template (content) (output_directive (code)) (content))
- HTML: (fragment (element (start_tag (tag_name)) (text) (end_tag (tag_name))))
- RUBY: (program (call receiver: (identifier) method: (identifier)))

There is a new `(text)` node due to space. I expect this text node, but I don't understand why it contains the text `<%= person.name %> ` (ruby code + space) and not just ` ` (space).
As I specify the HTML range to parse, I was expecting a text node containing only a single space.

Is it:
- an issue related to the HTML parser?
- an issue related to the ranges detection?
- the expected behaviour?

I think I'm missing something, but I don't know what. Please do not hesitate to ask for more details if I'm not clear.

Thank you for your help :rescue_worker_helmet:

**Comment by thibaultdalban** [comment]
Hello @maxbrunsfeld,

I'm wondering if you had time to check this issue or if there is a better place where I should post it?

Thank you.

**Comment by maxbrunsfeld** [comment]
In general, the Ruby and the HTML nodes are expected to overlap. For example, if there were a space before the `<%=`, then the `text` node's range would obviously contain the ruby code.

As for why the nodes overlap in this particular case, I'm not actually sure. It is somewhat  arbitrary whether the text node should start before or after the code block, and I can't remember the exact logic that applies to this case.

**Comment by thibaultdalban** [comment]
@maxbrunsfeld Thank you for your quick reply!
